spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: "jdbc:mysql://127.0.0.1:23306/parcial1?useSSL=false"
    password: mysql
    testOnBorrow: true
    max-wait: 8000
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: 'true'
        ddl-auto: create
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      mode: always
server:
  port: '8081'
